DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE AUTHORS
(
    ID     IDENTITY NOT NULL PRIMARY KEY,
    AUTHOR VARCHAR(255) UNIQUE
);

CREATE TABLE GENRES
(
    ID    IDENTITY NOT NULL PRIMARY KEY,
    GENRE VARCHAR(255) UNIQUE
);
CREATE TABLE BOOKS
(
    ID        IDENTITY NOT NULL PRIMARY KEY,
    NAME      VARCHAR(255),
    AUTHOR_ID BIGINT,
    CONSTRAINT UC_Book UNIQUE (NAME, AUTHOR_ID)
);

CREATE TABLE COMMENTS
(
    ID IDENTITY NOT NULL PRIMARY KEY,
    book_id bigint references BOOKS(id) on delete cascade,
    comment varchar(255)
);

CREATE TABLE BOOKS_GENRES
(
    ID       IDENTITY NOT NULL PRIMARY KEY,
    BOOK_ID  bigint not null,
    GENRE_ID bigint not null,
    CONSTRAINT UC_Book_genre UNIQUE (BOOK_ID, GENRE_ID)
);

ALTER TABLE BOOKS_GENRES
    ADD CONSTRAINT fk_books_genres_genres FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID) on delete cascade;
ALTER TABLE BOOKS_GENRES
    ADD CONSTRAINT fk_books_genres_books FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID) on delete cascade;
ALTER TABLE BOOKS
    ADD CONSTRAINT fk_author FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID) on delete cascade;
ALTER TABLE COMMENTS
    ADD CONSTRAINT fk_comments_books FOREIGN KEY (book_id) REFERENCES BOOKS (ID) on delete cascade;