spring:
  data:
    mongodb:
#      host: 127.0.0.1
      database: library
#      port: 27017

mongock:
#  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.mongock.changelog
